// localization.dart
class AppLocalizations {
  static const Map<String, Map<String, String>> localizedValues = {
    'ta': {
      'app_title': 'மோசடி கண்டறிதல்',
      'risk_level': 'அபாய நிலை',
      'risk_score': 'அபாய புள்ளி',
      'risk_factors': 'அபாய காரணிகள்',
      'why_flagged': 'ஏன் கொடியிடப்பட்டது?',
      'recommended_action': 'பரிந்துரைக்கப்பட்ட நடவடிக்கை',
      'xai_pipeline': 'விளக்கக்கூடிய AI வழிமுறை',
      'transaction': 'பரிவர்த்தனை',
      'message': 'செய்தி',
      'call_transcript': 'அழைப்பு உரை',
      'analyze': 'பகுப்பாய்வு செய்',
      'safe': 'பாதுகாப்பானது',
      'medium_risk': 'மிதமான அபாயம்',
      'high_risk': 'அதிக அபாயம்',
      'action_safe': 'எந்த நடவடிக்கையும் தேவையில்லை.',
      'action_high': 'பணத்தை அனுப்ப வேண்டாம். உடனடியாக இந்த எண்ணை தடுக்கவும்.'
    },
    'en': {
      'app_title': 'Scam Detector',
      'risk_level': 'Risk Level',
      'risk_score': 'Risk Score',
      'risk_factors': 'Risk Factors',
      'why_flagged': 'Why Flagged?',
      'recommended_action': 'Recommended Action',
      'xai_pipeline': 'Explainable AI Pipeline',
      'transaction': 'Transaction',
      'message': 'Message',
      'call_transcript': 'Call Transcript',
      'analyze': 'Analyze',
      'safe': 'Safe',
      'medium_risk': 'Medium Risk',
      'high_risk': 'High Risk',
      'action_safe': 'No action needed.',
      'action_high': 'Do not transfer money. Block this sender immediately.'
    },
    'hi': {
      'app_title': 'स्कैम डिटेक्टर',
      'risk_level': 'जोखिम का स्तर',
      'risk_score': 'जोखिम स्कोर',
      'risk_factors': 'जोखिम कारक',
      'why_flagged': 'क्यों फ्लैग किया गया?',
      'recommended_action': 'अनुशंसित कार्रवाई',
      'xai_pipeline': 'स्पष्टीकरणात्मक एआई पाइपलाइन',
      'transaction': 'लेन-देन',
      'message': 'संदेश',
      'call_transcript': 'कॉल ट्रांसक्रिप्ट',
      'analyze': 'विश्लेषण करें',
      'safe': 'सुरक्षित',
      'medium_risk': 'मध्यम जोखिम',
      'high_risk': 'उच्च जोखिम',
      'action_safe': 'किसी कार्रवाई की आवश्यकता नहीं है।',
      'action_high': 'पैसा न भेजें। इस नंबर को तुरंत ब्लॉक करें।'
    },
    'te': {
      'app_title': 'స్కామ్ డిటెక్టర్',
      'risk_level': 'ప్రమాద స్థాయి',
      'risk_score': 'ప్రమాద స్కోరు',
      'risk_factors': 'ప్రమాద కారకాలు',
      'why_flagged': 'ఎందుకు ఫ్లాగ్ చేయబడింది?',
      'recommended_action': 'సిఫార్సు చేసిన చర్య',
      'xai_pipeline': 'వివరణాత్మక AI పైప్‌లైన్',
      'transaction': 'లావాదేవీ',
      'message': 'సందేశం',
      'call_transcript': 'కాల్ ట్రాన్స్‌క్రిప్ట్',
      'analyze': 'విశ్లేషించండి',
      'safe': 'సురక్షితం',
      'medium_risk': 'మధ్యస్థ ప్రమాదం',
      'high_risk': 'అధిక ప్రమాదం',
      'action_safe': 'చర్య అవసరం లేదు.',
      'action_high': 'డబ్బు పంపవద్దు. వెంటనే ఈ నంబర్‌ను బ్లాక్ చేయండి.'
    },
    'ml': {
      'app_title': 'സ്കാം ഡിറ്റക്ടർ',
      'risk_level': 'അപകട നില',
      'risk_score': 'അപകട സ്കോർ',
      'risk_factors': 'അപകട ഘടകങ്ങൾ',
      'why_flagged': 'എന്തുകൊണ്ട് ഫ്ലാഗ് ചെയ്തു?',
      'recommended_action': 'ശിപാർശ ചെയ്യുന്ന നടപടി',
      'xai_pipeline': 'വിശദീകരിക്കാവുന്ന AI പൈപ്പ്‌ലൈൻ',
      'transaction': 'ഇടപാട്',
      'message': 'സന്ദേശം',
      'call_transcript': 'കോൾ ട്രാൻസ്ക്രിപ്റ്റ്',
      'analyze': 'വിശകലനം ചെയ്യുക',
      'safe': 'സുരക്ഷിതം',
      'medium_risk': 'മിതമായ അപകടസാധ്യത',
      'high_risk': 'ഉയർന്ന അപകടസാധ്യത',
      'action_safe': 'നടപടിയൊന്നും ആവശ്യമില്ല.',
      'action_high': 'പണം അയക്കരുത്. ഈ നമ്പർ ഉടൻ ബ്ലോക്ക് ചെയ്യുക.'
    },
    'kn': {
      'app_title': 'ಸ್ಕ್ಯಾಮ್ ಡಿಟೆಕ್ಟರ್',
      'risk_level': 'ಅಪಾಯದ ಮಟ್ಟ',
      'risk_score': 'ಅಪಾಯದ ಸ್ಕೋರ್',
      'risk_factors': 'ಅಪಾಯದ ಅಂಶಗಳು',
      'why_flagged': 'ಏಕೆ ಫ್ಲ್ಯಾಗ್ ಮಾಡಲಾಗಿದೆ?',
      'recommended_action': 'ಶಿಫಾರಸು ಮಾಡಿದ ಕ್ರಮ',
      'xai_pipeline': 'ವಿವರಣಾತ್ಮಕ AI ಪೈಪ್‌ಲೈನ್',
      'transaction': 'ವಹಿವಾಟು',
      'message': 'ಸಂದೇಶ',
      'call_transcript': 'ಕಾಲ್ ట్రాನ್ಸ್‌ಕ್ರಿಪ್ಟ್',
      'analyze': 'ವಿಶ್ಲೇಷಿಸಿ',
      'safe': 'ಸುರಕ್ಷಿತ',
      'medium_risk': 'ಮಧ್ಯಮ ಅಪಾಯ',
      'high_risk': 'ಹೆಚ್ಚಿನ ಅಪಾಯ',
      'action_safe': 'ಯಾವುದೇ ಕ್ರಮ ಅಗತ್ಯವಿಲ್ಲ.',
      'action_high': 'ಹಣವನ್ನು ಕಳುಹಿಸಬೇಡಿ. ಈ ಸಂಖ್ಯೆಯನ್ನು ತಕ್ಷಣವೇ ನಿರ್ಬಂಧಿಸಿ.'
    },
    'mr': {
      'app_title': 'स्कॅम डिटेक्टर',
      'risk_level': 'धोका पातळी',
      'risk_score': 'धोका स्कोर',
      'risk_factors': 'धोका घटक',
      'why_flagged': 'ध्वजांकित का केले?',
      'recommended_action': 'शिफारस केलेली कारवाई',
      'xai_pipeline': 'स्पष्टीकरणात्मक AI पाइपलाइन',
      'transaction': 'व्यवहार',
      'message': 'संदेश',
      'call_transcript': 'कॉल प्रतिलेख',
      'analyze': 'विश्लेषण करा',
      'safe': 'सुरक्षित',
      'medium_risk': 'मध्यम धोका',
      'high_risk': 'उच्च धोका',
      'action_safe': 'कोणत्याही कारवाईची गरज नाही.',
      'action_high': 'पैसे पाठवू नका. हा नंबर त्वरित ब्लॉक करा.'
    }
  };

  static String getText(String key, String langCode) {
    return localizedValues[langCode]?[key] ?? localizedValues['en']![key]!;
  }
}
